# Generated by Django 5.1 on 2024-08-27 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name_km', models.CharField(max_length=32, verbose_name='Level name in Khmer')),
                ('name_en', models.CharField(blank=True, max_length=32, null=True, verbose_name='Level name in Latin')),
            ],
        ),
        migrations.CreateModel(
            name='Gazetteer',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('level', models.PositiveSmallIntegerField()),
                ('name_km', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mapapp.gazetteer')),
                ('updated_by', models.ForeignKey(db_column='updated_by', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
